[package]
name = "theatre_bill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
currency_rs = "1.3.0"
serde_json = "1.0.114"
